import json
import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=ROOT)


def main():
    protocol_version = os.environ["PROTOCOL_VERSION"]
    new_version = os.environ["NEW_VERSION"]
    app_id = os.environ["HEGEL_RELEASE_APP_ID"]

    versions_path = ROOT / "public" / "api" / "versions.json"
    versions = json.loads(versions_path.read_text())

    if protocol_version in versions:
        print(f"Protocol version {protocol_version} already mapped, nothing to do")
        return

    versions[protocol_version] = new_version
    # Sort by protocol version (numeric)
    sorted_versions = dict(sorted(versions.items(), key=lambda kv: float(kv[0])))
    versions_path.write_text(json.dumps(sorted_versions, indent=2) + "\n")

    git("config", "user.name", "hegel-release[bot]")
    git("config", "user.email", f"{app_id}+hegel-release[bot]@users.noreply.github.com")

    git("checkout", "-b", "ci/update-versions")
    git("add", "public/api/versions.json")
    git("commit", "-m", f"Add protocol version {protocol_version} mapping")
    git("push", "--force", "origin", "ci/update-versions")

    # Check if PR already exists
    result = subprocess.run(
        [
            "gh",
            "pr",
            "list",
            "--head",
            "ci/update-versions",
            "--state",
            "open",
            "--json",
            "number",
        ],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    has_open_pr = result.returncode == 0 and result.stdout.strip() not in ("", "[]")

    title = f"Add protocol version {protocol_version} mapping"
    update_url = "https://github.com/hegeldev/website/blob/main/.github/workflows/update-versions.yml"
    core_url = "https://github.com/hegeldev/hegel-core/blob/main/.github/workflows/ci.yml"
    body = (
        f"Maps protocol version `{protocol_version}` to hegel-core `v{new_version}`.\n"
        "\n"
        "---\n"
        "\n"
        f"*This PR was automatically generated by [update-versions.yml]({update_url})"
        f" after a trigger by [this hegel-core workflow]({core_url}).*"
    )
    if has_open_pr:
        subprocess.run(
            [
                "gh",
                "pr",
                "edit",
                "ci/update-versions",
                "--title",
                title,
                "--body",
                body,
            ],
            check=True,
            cwd=ROOT,
        )
    else:
        subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )


if __name__ == "__main__":
    main()
